# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'product.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(620, 631)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 171, 170))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(190, 0, 411, 171))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_2.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_2.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_2.addWidget(self.lineEdit_6)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 180, 571, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bSimpan = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bSimpan.setFont(font)
        self.bSimpan.setObjectName("bSimpan")
        self.horizontalLayout.addWidget(self.bSimpan)
        self.bUbah = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bUbah.setFont(font)
        self.bUbah.setObjectName("bUbah")
        self.horizontalLayout.addWidget(self.bUbah)
        self.bHapus = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bHapus.setFont(font)
        self.bHapus.setObjectName("bHapus")
        self.horizontalLayout.addWidget(self.bHapus)
        self.bLoad = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bLoad.setFont(font)
        self.bLoad.setObjectName("bLoad")
        self.horizontalLayout.addWidget(self.bLoad)
        self.lHasil = QtWidgets.QLabel(Form)
        self.lHasil.setGeometry(QtCore.QRect(10, 250, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lHasil.setFont(font)
        self.lHasil.setObjectName("lHasil")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 310, 581, 231))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget_3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 550, 581, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_2.addWidget(self.lineEdit_7)
        self.bFilter = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bFilter.setFont(font)
        self.bFilter.setObjectName("bFilter")
        self.horizontalLayout_2.addWidget(self.bFilter)

        self.bSimpan.clicked.connect(self.Simpan)
        self.bLoad.clicked.connect(self.load)
        self.bUbah.clicked.connect(self.ubah)
        self.bHapus.clicked.connect(self.hapus)
        self.bFilter.clicked.connect(self.filter)
        self.tableWidget.cellClicked.connect(self.getId)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def getId(self,row):
        try:
            iditem = self.tableWidget.item(row,0)
            barcodeitem = self.tableWidget.item(row,1)
            nameitem = self.tableWidget.item(row,2)
            kategoriitem = self.tableWidget.item(row,3)
            qtyitem = self.tableWidget.item(row,4)
            hargaritem = self.tableWidget.item(row,5)

            if iditem :
                valueid = iditem.text()
                valuebarcode = barcodeitem.text()
                valuename = nameitem.text()
                valuekategori = kategoriitem.text()
                valueqty = qtyitem.text()
                valueharga = hargaritem.text()
                self.lineEdit.setText(valueid)
                self.lineEdit_2.setText(valuebarcode)
                self.lineEdit_3.setText(valuename)
                self.lineEdit_4.setText(valuekategori)
                self.lineEdit_5.setText(valueqty)
                self.lineEdit_6.setText(valueharga)
            self.lHasil.setText("Data Kategori Berhasil Dipillih")
        except mc.Error as err:
            self.lHasil.setText("Data Kategori Gagal Dipilih")
    
    def Simpan(self):
        try:
            mydb = mc.connect(
            host ="localhost",
            user ="root",
            password ="",
            database ="db_penjualan"
        )   
            cursor = mydb.cursor()
            id = self.lineEdit.text()
            barcode = self.lineEdit_2.text()
            name = self.lineEdit_3.text()
            kategori = self.lineEdit_4.text()
            qty = self.lineEdit_5.text()
            harga = self.lineEdit_6.text()
            sql ="INSERT INTO product (id,barcode,name,kategori,qty,harga) VALUES (%s,%s,%s,%s,%s,%s)"
            val = (id,barcode,name,kategori,qty,harga)
            cursor.execute(sql,val)
            mydb.commit()
            self.lHasil.setText("Data Product Berhasil Disimpan")
            self.lineEdit.setText("")
            self.lineEdit_2.setText("")
            self.lineEdit_3.setText("")
            self.lineEdit_4.setText("")
            self.lineEdit_5.setText("")
            self.lineEdit_6.setText("")
        except mc.Error as err:
            self.lHasil.setText("Data Product Gagal Disimpan")

    
    def ubah(self):
        try:
            mydb = mc.connect(
            host ="localhost",
            user ="root",
            password ="",
            database ="db_penjualan"
        )   
            cursor = mydb.cursor()
            id = self.lineEdit.text()
            barcode = self.lineEdit_2.text()
            name = self.lineEdit_3.text()
            kategori = self.lineEdit_4.text()
            qty = self.lineEdit_5.text()
            harga = self.lineEdit_6.text()
            sql = "UPDATE product SET barcode = %s, name = %s, kategori = %s, qty = %s, harga = %s WHERE id = %s"
            val = (barcode,name,kategori,qty,harga,id)

            cursor.execute(sql,val)
            mydb.commit()
            self.lHasil.setText("Data Product Berhasil Update")
            self.lineEdit.setText("")
            self.lineEdit_2.setText("")
            self.lineEdit_3.setText("")
            self.lineEdit_4.setText("")
            self.lineEdit_5.setText("")
            self.lineEdit_6.setText("")
        except mc.Error as err:
            self.lHasil.setText("Data Product Gagal Update")


    def hapus(self):
        try:
            mydb = mc.connect(
            host ="localhost",
            user ="root",
            password ="",
            database ="db_penjualan"
        )
            cursor = mydb.cursor()
            id = self.lineEdit.text()
            sql ="DELETE FROM product WHERE id = %s"
            val = (id,)
            cursor.execute(sql,val)
            mydb.commit()
            self.lHasil.setText("Data Product Berhasil Dihapus")
            self.lineEdit.setText("")
            self.lineEdit_2.setText("")
            self.lineEdit_3.setText("")
            self.lineEdit_4.setText("")
            self.lineEdit_5.setText("")
            self.lineEdit_6.setText("")
        except mc.Error as err:
            self.lHasil.setText("Data Procust Gagal Dihapus")


    def load(self):
        try:
            mydb = mc.connect(
            host ="localhost",
            user ="root",
            password ="",
            database ="db_penjualan"
        )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT * FROM product ORDER BY id ASC")
            result = mycursor.fetchall()
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number,column_number, QTableWidgetItem(str(data)))
            self.lHasil.setText("Data Product Berhasil DiTampilkan")
        except mc.Error as err:
            self.lHasil.setText("Data Product Gagal DiTampilkan")


    def filter(self):
        try:
            mydb = mc.connect(
            host ="localhost",
            user ="root",
            password ="",
            database ="db_penjualan"
        )
            mycursor = mydb.cursor()
            srckat =self.lHasil.text()
            sql = "SELECT * FROM product WHERE id LIKE %s OR barcode LIKE %s ORDER BY id ASC"
            val = (f"%{srckat}%", f"%{srckat}%")
            mycursor.execute(sql,val)
            result = mycursor.fetchall()
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number,column_number, QTableWidgetItem(str(data)))
            self.lHasil.setText("Hasil Search Data product ")
        except mc.Error as err:
            self.lHasil.setText("Pencarian Gagal")



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Id"))
        self.label_2.setText(_translate("Form", "Barcode"))
        self.label_3.setText(_translate("Form", "Name"))
        self.label_4.setText(_translate("Form", "Kategori"))
        self.label_5.setText(_translate("Form", "QTY"))
        self.label_6.setText(_translate("Form", "Harga"))
        self.bSimpan.setText(_translate("Form", "Simpan"))
        self.bUbah.setText(_translate("Form", "Ubah"))
        self.bHapus.setText(_translate("Form", "Hapus"))
        self.bLoad.setText(_translate("Form", "Load"))
        self.lHasil.setText(_translate("Form", "Hasil"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Barcode"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Kategori"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Qty"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Harga"))
        self.bFilter.setText(_translate("Form", "Filter Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
